name: OpenSSF Criticality Score

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  criticality:
    name: Calculate Criticality Score
    runs-on: ubuntu-latest

    steps:
      - name: Run OpenSSF Criticality Score
        uses: ossf/criticality_score@v2
        with:
          repo: https://github.com/DTDucas/chm-converter
